import pandas as pd

analysis = pd.read_excel("data/raw/analysis.xlsx", header=1)
balancesheet = pd.read_excel("data/raw/balancesheet.xlsx", header=1)
cashflow = pd.read_excel("data/raw/cashflow.xlsx", header=1)
companies = pd.read_excel("data/raw/companies.xlsx", header=1)
documents = pd.read_excel("data/raw/documents.xlsx", header=1)
financial_ratios = pd.read_excel("data/raw/financial_ratios.xlsx", header=1)
market_cap = pd.read_excel("data/raw/market_cap.xlsx", header=1)
peer_groups = pd.read_excel("data/raw/peer_groups.xlsx", header=1)
profitandloss = pd.read_excel("data/raw/profitandloss.xlsx", header=1)
prosandcons = pd.read_excel("data/raw/prosandcons.xlsx", header=1)
sectors = pd.read_excel("data/raw/sectors.xlsx", header=1)
stock_prices = pd.read_excel("data/raw/stock_prices.xlsx", header=1)

print("Analysis:", analysis.shape)
print("Balance Sheet:", balancesheet.shape)
print("Cash Flow:", cashflow.shape)
print("Companies:", companies.shape)
print("Documents:", documents.shape)
print("Financial Ratios:", financial_ratios.shape)
print("Market Cap:", market_cap.shape)
print("Peer Groups:", peer_groups.shape)
print("Profit & Loss:", profitandloss.shape)
print("Pros & Cons:", prosandcons.shape)
print("Sectors:", sectors.shape)
print("Stock Prices:", stock_prices.shape)

print(analysis.head(10))
print(balancesheet.head(10))
print(cashflow.head(10))    
print(companies.head(10))
print(documents.head(10))
print(financial_ratios.head(10))
print(market_cap.head(10))
print(peer_groups.head(10))
print(profitandloss.head(10))
print(prosandcons.head(10))
print(sectors.head(10))
print(stock_prices.head(10))